//import  { style } from "../../blocks/hero-marquee/hero-marquee.css.js";
export const hero_marquee = () => {
    return "<div class=\"hero-marquee bg-bottom-mobile bg-top-tablet static-links media-cover media-hidden-mobile media-hidden-tablet con-block has-bg\" daa-lh=\"b1|hero-marquee\"><div class=\"background\"><div data-valign=\"middle\" class=\"mobile-only expand-background\"></div><div data-valign=\"middle\" class=\"tablet-only desktop-only\"><video playsinline=\"\" autoplay=\"\" muted=\"\" loop=\"\"><source src=\"https://main--milo-demo--rohitsahu.hlx.page/libs/media_11def647aaa61ee7c3f1798b92ce6441c459989b9.mp4\" type=\"video/mp4\"></video></div></div><div class=\"foreground cols-2\"> <div data-valign=\"middle\" class=\"copy\"><div class=\"main-copy\"> <p class=\"detail-l lockup-area\"><picture><img loading=\"lazy\" src=\"https://www.adobe.com/cc-shared/assets/img/product-icons/svg/photoshop-40.svg\"></picture> <strong>Photoshop</strong></p> <h2 id=\"go-from-inspiration-to-creation-faster\" class=\"heading-xxl\"><strong>Go from inspiration to creation faster.</strong></h2> <p class=\"body-m\">Explore quick new ways to edit images and text with new innovations in Photoshop. Get Photoshop in Creative Cloud All Apps and save 40%. <span is=\"inline-price\" data-display-old-price=\"true\" data-quantity=\"1\" data-template=\"strikethrough\" data-wcs-osi=\"Mutn1LYoGojkrcMdCLO7LQlx1FyTHw27ETsfLv0h8DQ\" class=\"placeholder-failed\"></span> <span is=\"inline-price\" data-display-old-price=\"true\" data-quantity=\"1\" data-template=\"price\" data-wcs-osi=\"Mutn1LYoGojkrcMdCLO7LQlx1FyTHw27ETsfLv0h8DQ\" class=\"placeholder-failed\"></span> First year only. Ends Aug 4. <a href=\"https://www.stage.adobe.com/offer-terms/cc_full_special_offer.html\" daa-ll=\"See terms-1--Go from inspiration \">See terms</a>.</p> <p class=\"body-m action-area\"><a href=\"https://www.stage.adobe.com/creativecloud/plans.html?plan=individual\" class=\"con-button blue button-xl button-justified-mobile\" daa-ll=\"Buy now-2--Go from inspiration \">Buy now</a></p> </div></div> <div data-valign=\"middle\" class=\"empty-asset\"></div> </div> </div>"
}

export const aside_l = () => {
    return "<div class=\"aside large con-block\" daa-lh=\"b2|aside\"> <div class=\"background\"> <div data-valign=\"middle\" class=\"mobile-only expand-background\"></div> <div data-valign=\"middle\" class=\"tablet-only desktop-only expand-background\" style=\"background: linear-gradient(49deg, rgb(36, 160, 219) 0%, rgb(32, 188, 163) 35%, rgb(26, 208, 127) 100%);\"></div> </div> <div class=\"foreground container\"> <div data-valign=\"middle\" class=\"image\"><video playsinline=\"\" autoplay=\"\" muted=\"\" loop=\"\"> <source src=\"https://main--milo-demo--rohitsahu.hlx.page/libs/media_1d73928ecf92f5ac87654a20e9bba22ac39e626f2.mp4\" type=\"video/mp4\"> </video></div> <div data-valign=\"middle\" class=\"text\"> <p class=\"detail-m\"><strong>REMOVE BACKGROUND</strong></p> <h3 id=\"swap-out-your-scene\" class=\"heading-xl\"><strong>Swap out your scene.</strong></h3> <p class=\"body-s\">Use intuitive tools to make complex edits in a few steps. Replace a blah background with a whole new setting and give your images a natural, custom look.</p> </div> </div> </div>";
}

export const aside_m = () => {
    return "<div class=\"aside large con-block\" daa-lh=\"b3|aside\"> <div class=\"background\"> <div data-valign=\"middle\" class=\"mobile-only expand-background\"></div> <div data-valign=\"middle\" class=\"tablet-only desktop-only expand-background\" style=\"background: linear-gradient(49deg, rgb(36, 160, 219) 0%, rgb(32, 188, 163) 35%, rgb(26, 208, 127) 100%);\"></div> </div> <div class=\"foreground container\"> <div data-valign=\"middle\" class=\"text\"> <p class=\"detail-m\"><strong>COMBINE IMAGES</strong></p> <h3 id=\"create-something-totally-new\" class=\"heading-xl\"><strong>Create something totally new.</strong></h3> <p class=\"body-s\">With best-in-class design tools at your fingertips it’s simple to merge images. Make a composite with bits and pieces of multiple images to create the unexpected.</p> </div> <div data-valign=\"middle\" class=\"image\"><video playsinline=\"\" autoplay=\"\" muted=\"\" loop=\"\"> <source src=\"https://main--milo-demo--rohitsahu.hlx.page/libs/media_1dfb27bf082a3d5500d7c54e1fe13d006b417a6a1.mp4\" type=\"video/mp4\"> </video></div> </div> </div>";
}

 export const aside_in = () => {
    return "<div class=\"aside large split half dark l-button con-block split-right\" daa-lh=\"b1|aside|nopzn--nopzn|indesign--mobile-marquee\" style=\"background: rgb(211, 131, 78);\"> <div class=\"foreground container\"> <div data-valign=\"middle\" class=\"text\"> <p class=\"detail-m\">Advertising graphics</p> <h2 id=\"design-interactive-catalogues-and-brochures\" class=\"heading-xl\">Design interactive catalogues and brochures.</h2> <p class=\"body-s\">Craft elevated product marketing materials that deliver immersive branding for both digital and print.</p> </div> </div> <div data-valign=\"middle\" class=\"image split-image\"><video playsinline=\"\" autoplay=\"\" muted=\"\" loop=\"\"> <source src=\"https://images-tv.adobe.com/mpcv3/7145/9758d508-941a-4b9e-9fb6-f44918b89bb1_1708023376.1920x1080at3000_h264.mp4\" type=\"video/mp4\"> </video></div></div>";
 }

 export const aside_in_2 = () => {
    return "<div class=\"aside large split half dark l-button con-block split-left\" style=\"background: rgb(26, 26, 26);\" daa-lh=\"b2|aside|nopzn--nopzn|indesign--mobile-marquee\"> <div class=\"foreground container\"> <div data-valign=\"middle\" class=\"text\"> <p class=\"detail-m\">Multipage layouts</p> <h2 id=\"make-an-impact-with-print\" class=\"heading-xl\">Make an impact with print.</h2> <p class=\"body-s\">Lay out designs with thousands of fonts and time-saving layout and typesetting features and then fine-tune every detail with precise editing tools.</p> </div> </div> <div data-valign=\"middle\" class=\"image split-image\"><video playsinline=\"\" autoplay=\"\" muted=\"\" loop=\"\"> <source src=\"https://images-tv.adobe.com/mpcv3/7145/8d60e6a1-63a9-45c2-ae17-8bb5e491b7c0_1708023747.1920x1080at3000_h264.mp4\" type=\"video/mp4\"> </video></div></div>";
 }

 export const aside_in_3 = () => {
    return "<div class=\"aside large split half dark l-button con-block split-right\" style=\"background: rgb(0, 89, 97);\" daa-lh=\"b3|aside|nopzn--nopzn|indesign--mobile-marquee\"> <div class=\"foreground container\"> <div data-valign=\"middle\" class=\"text\"> <p class=\"detail-m\"><strong>Seamless collaboration</strong></p> <h2 id=\"build-a-brand-together\" class=\"heading-xl\">Build a brand together.</h2> <p class=\"body-s\">Speed up the review process with features that make it simple to share assets, add feedback and collaborate with stakeholders.</p> </div> </div> <div data-valign=\"middle\" class=\"image split-image\"><video playsinline=\"\" autoplay=\"\" muted=\"\" loop=\"\"> <source src=\"https://images-tv.adobe.com/mpcv3/7145/2620b0a5-4569-468f-83c7-08ee746ad9cc_1708023886.1920x1080at3000_h264.mp4\" type=\"video/mp4\"> </video></div></div>";
 }