//import  { style } from "../../blocks/hero-marquee/hero-marquee.css.js";
export const hero_marquee = () => {
    return "<div class=\"hero-marquee bg-bottom-mobile bg-top-tablet static-links media-cover media-hidden-mobile media-hidden-tablet con-block has-bg\" daa-lh=\"b1|hero-marquee\"><div class=\"background\"><div data-valign=\"middle\" class=\"mobile-only expand-background\"></div><div data-valign=\"middle\" class=\"tablet-only desktop-only\"><video playsinline=\"\" autoplay=\"\" muted=\"\" loop=\"\"><source src=\"https://main--milo-demo--rohitsahu.hlx.page/libs/media_11def647aaa61ee7c3f1798b92ce6441c459989b9.mp4\" type=\"video/mp4\"></video></div></div><div class=\"foreground cols-2\"> <div data-valign=\"middle\" class=\"copy\"><div class=\"main-copy\"> <p class=\"detail-l lockup-area\"><picture><img loading=\"lazy\" src=\"https://www.adobe.com/cc-shared/assets/img/product-icons/svg/photoshop-40.svg\"></picture> <strong>Photoshop</strong></p> <h2 id=\"go-from-inspiration-to-creation-faster\" class=\"heading-xxl\"><strong>Go from inspiration to creation faster.</strong></h2> <p class=\"body-m\">Explore quick new ways to edit images and text with new innovations in Photoshop. Get Photoshop in Creative Cloud All Apps and save 40%. <span is=\"inline-price\" data-display-old-price=\"true\" data-quantity=\"1\" data-template=\"strikethrough\" data-wcs-osi=\"Mutn1LYoGojkrcMdCLO7LQlx1FyTHw27ETsfLv0h8DQ\" class=\"placeholder-failed\"></span> <span is=\"inline-price\" data-display-old-price=\"true\" data-quantity=\"1\" data-template=\"price\" data-wcs-osi=\"Mutn1LYoGojkrcMdCLO7LQlx1FyTHw27ETsfLv0h8DQ\" class=\"placeholder-failed\"></span> First year only. Ends Aug 4. <a href=\"https://www.stage.adobe.com/offer-terms/cc_full_special_offer.html\" daa-ll=\"See terms-1--Go from inspiration \">See terms</a>.</p> <p class=\"body-m action-area\"><a href=\"https://www.stage.adobe.com/creativecloud/plans.html?plan=individual\" class=\"con-button blue button-xl button-justified-mobile\" daa-ll=\"Buy now-2--Go from inspiration \">Buy now</a></p> </div></div> <div data-valign=\"middle\" class=\"empty-asset\"></div> </div> </div>"
}

export const aside_l = () => {
    return "<div class=\"aside large con-block\" daa-lh=\"b2|aside\"> <div class=\"background\"> <div data-valign=\"middle\" class=\"mobile-only expand-background\"></div> <div data-valign=\"middle\" class=\"tablet-only desktop-only expand-background\" style=\"background: linear-gradient(49deg, rgb(36, 160, 219) 0%, rgb(32, 188, 163) 35%, rgb(26, 208, 127) 100%);\"></div> </div> <div class=\"foreground container\"> <div data-valign=\"middle\" class=\"image\"><video playsinline=\"\" autoplay=\"\" muted=\"\" loop=\"\"> <source src=\"https://main--milo-demo--rohitsahu.hlx.page/libs/media_1d73928ecf92f5ac87654a20e9bba22ac39e626f2.mp4\" type=\"video/mp4\"> </video></div> <div data-valign=\"middle\" class=\"text\"> <p class=\"detail-m\"><strong>REMOVE BACKGROUND</strong></p> <h3 id=\"swap-out-your-scene\" class=\"heading-xl\"><strong>Swap out your scene.</strong></h3> <p class=\"body-s\">Use intuitive tools to make complex edits in a few steps. Replace a blah background with a whole new setting and give your images a natural, custom look.</p> </div> </div> </div>";
}

export const aside_m = () => {
    return "<div class=\"aside large con-block\" daa-lh=\"b3|aside\"> <div class=\"background\"> <div data-valign=\"middle\" class=\"mobile-only expand-background\"></div> <div data-valign=\"middle\" class=\"tablet-only desktop-only expand-background\" style=\"background: linear-gradient(49deg, rgb(36, 160, 219) 0%, rgb(32, 188, 163) 35%, rgb(26, 208, 127) 100%);\"></div> </div> <div class=\"foreground container\"> <div data-valign=\"middle\" class=\"text\"> <p class=\"detail-m\"><strong>COMBINE IMAGES</strong></p> <h3 id=\"create-something-totally-new\" class=\"heading-xl\"><strong>Create something totally new.</strong></h3> <p class=\"body-s\">With best-in-class design tools at your fingertips it’s simple to merge images. Make a composite with bits and pieces of multiple images to create the unexpected.</p> </div> <div data-valign=\"middle\" class=\"image\"><video playsinline=\"\" autoplay=\"\" muted=\"\" loop=\"\"> <source src=\"https://main--milo-demo--rohitsahu.hlx.page/libs/media_1dfb27bf082a3d5500d7c54e1fe13d006b417a6a1.mp4\" type=\"video/mp4\"> </video></div> </div> </div>";
}

